[package]
name = "chacha20poly1305"
version = "0.4.0"
description = """
Pure Rust implementation of the ChaCha20Poly1305 Authenticated Encryption
with Additional Data Cipher (RFC 8439) with optional architecture-specific
hardware acceleration. Also contains implementations of the XChaCha20Poly1305
extended nonce variant of ChaCha20Poly1305, and the reduced-round
ChaCha8Poly1305 and ChaCha12Poly1305 lightweight variants.
"""
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/chacha20poly1305"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "chacha20", "poly1305", "xchacha20", "xchacha20poly1305"]
categories = ["cryptography", "no-std"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
aead = { version = "0.2", default-features = false }
chacha20 = { version = "0.3", features = ["zeroize"], optional = true }
poly1305 = "0.5"
stream-cipher = "0.3"
zeroize = { version = "1", default-features = false }

[dev-dependencies]
criterion = "0.3.0"
criterion-cycles-per-byte = "0.1.1"

[features]
default = ["alloc", "chacha20", "xchacha20poly1305"]
alloc = ["aead/alloc"]
heapless = ["aead/heapless"]
reduced-round = ["chacha20"]
xchacha20poly1305 = ["chacha20/xchacha20"]

[[bench]]
name = "chacha20poly1305"
harness = false

[package.metadata.docs.rs]
all-features = true
