[package]
name = "aes-siv"
version = "0.7.0"
description = """
Pure Rust implementation of the AES-SIV Misuse-Resistant Authenticated
Encryption Cipher (RFC 5297) with optional architecture-specific
hardware acceleration
"""
authors = ["RustCrypto Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/aes-siv"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "encryption", "siv"]
categories = ["cryptography", "no-std"]
rust-version = "1.72"

[dependencies]
aead = "=0.6.0-pre.0"
aes = "=0.9.0-pre"
cipher = "=0.5.0-pre.4"
cmac = "0.8.0-pre"
ctr = "=0.10.0-pre"
dbl = "0.4.0-pre.4"
digest = { version = "0.11.0-pre.8", features = ["mac"] }
zeroize = { version = "1", default-features = false }

# optional dependencies
pmac = { version = "0.8.0-pre", optional = true }

[dev-dependencies]
blobby = "0.3"
hex-literal = "0.3"

[features]
default = ["alloc", "getrandom"]
std = ["aead/std", "alloc"]
alloc = ["aead/alloc"]
arrayvec = ["aead/arrayvec"]
getrandom  = ["aead/getrandom", "rand_core"]
heapless = ["aead/heapless"]
rand_core = ["aead/rand_core"]
stream = ["aead/stream"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
