[package]
name = "ccm"
version = "0.4.4"
description = "Generic implementation of the Counter with CBC-MAC (CCM) mode"
authors = ["RustCrypto Developers"]
edition = "2018"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/ccm"
homepage = "https://github.com/RustCrypto/AEADs"
repository = "https://github.com/RustCrypto/AEADs/tree/master/ccm"
categories = ["cryptography", "no-std"]
keywords = ["encryption", "aead"]

[dependencies]
aead = { version = "0.4", default-features = false }
cipher = { version = "0.3", default-features = false }
ctr = { version = "0.9", default-features = false }
subtle = { version = ">=2, <2.5", default-features = false }

[dev-dependencies]
aead = { version = "0.4", features = ["dev"], default-features = false }
aes = { version = "0.7", features = ["force-soft"] } # Uses `force-soft` for MSRV 1.41
hex-literal = "0.2"

[features]
default = ["alloc"]
std = ["aead/std", "alloc"]
alloc = ["aead/alloc"]
heapless = ["aead/heapless"]
stream = ["aead/stream"]
