name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
      - .github/workflows/security-audit.yml
  push:
    branches: master
    paths: Cargo.lock
  schedule:
    - cron: "0 0 * * *"

jobs:
  security_audit:
    name: Security Audit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Cache cargo bin
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-audit-v0.22.0
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
