[package]
name = "xaes-256-gcm"
version = "0.0.1-pre.0"
description = """
Pure Rust implementation of the XAES-256-GCM extended-nonce Authenticated
Encryption with Associated Data (AEAD).
"""
authors = ["RustCrypto Developers"]
edition = "2021"
license = "Apache-2.0 OR MIT"
readme = "README.md"
documentation = "https://docs.rs/xaes-256-gcm"
repository = "https://github.com/RustCrypto/AEADs"
keywords = ["aead", "aes", "xaes", "encryption", "extended-nonce"]
categories = ["cryptography", "no-std"]
rust-version = "1.72"

[dependencies]
aead = { version = "0.6.0-rc.0", default-features = false }
aes = "=0.9.0-pre.2"
aes-gcm = { version = "=0.11.0-pre.2", default-features = false, features = ["aes"] }
cipher = "=0.5.0-pre.7"

[dev-dependencies]
aead = { version = "0.6.0-rc.0", features = ["dev"], default-features = false }
hex-literal = "0.4"

[features]
default = ["alloc", "getrandom"]
std = ["aead/std", "aes-gcm/std", "cipher/std", "alloc"]
alloc = ["aead/alloc", "aes-gcm/alloc"]
arrayvec = ["aead/arrayvec", "aes-gcm/arrayvec"]
getrandom = ["aead/getrandom", "aes-gcm/getrandom", "rand_core"]
heapless = ["aead/heapless", "aes-gcm/heapless"]
rand_core = ["aead/rand_core", "aes-gcm/rand_core"]
stream = ["aead/stream", "aes-gcm/stream"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
